/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.event.MouseListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RYZEN
 */
public class PanelVenderAceptar extends javax.swing.JPanel {
    
    DefaultTableModel modelo;
    private boolean btnVerActivo = false;
    private boolean btnEditarActivo = false;
    private boolean btnEliminarActivo = false;

    /**
     * Creates new form PanelDashboard
     */
    public PanelVenderAceptar() {
        initComponents();
        setSize(1086, 503);
        
        modelo = (DefaultTableModel) tablaAfiliados.getModel();

    }
    
    
    
    public void agregarDatosTabla(String[] datos){
        modelo.addRow(datos);
    }
    
    public void addBtnAceptarListener(MouseListener listener){
        btnAceptar.addMouseListener(listener);
    }
    
    public void activarBotones(){
        btnEditarActivo = true;
        setBotonInactivo("Aceptar", btnAceptar);
    }
    
    private void setBotonActivo(String boton, JLabel imagenBoton){

        Icon btnActivo = new ImageIcon("src//Imagenes//BotonesCRUD//00-"+boton+"Activo.png"); 
        imagenBoton.setIcon(btnActivo);

        
        
    }
    
    private void setBotonInactivo(String boton, JLabel imagenBoton){
        Icon btnInactivo = new ImageIcon("src//Imagenes//BotonesCRUD//00-"+boton+"Inactivo.png"); 
        imagenBoton.setIcon(btnInactivo);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAfiliados = new javax.swing.JTable();
        fondoAfiliados = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1086, 503));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonesCRUD/00-AceptarInactivo.png"))); // NOI18N
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 144, 55));

        tablaAfiliados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Unidades Disponibles", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAfiliados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaAfiliados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaAfiliados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaAfiliados);
        if (tablaAfiliados.getColumnModel().getColumnCount() > 0) {
            tablaAfiliados.getColumnModel().getColumn(0).setResizable(false);
            tablaAfiliados.getColumnModel().getColumn(1).setResizable(false);
            tablaAfiliados.getColumnModel().getColumn(2).setResizable(false);
            tablaAfiliados.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 790, 380));

        fondoAfiliados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesPaneles/00-PanelAfiliadosFondo-img.png"))); // NOI18N
        add(fondoAfiliados, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1090, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        setBotonActivo("Aceptar", btnAceptar);
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        setBotonInactivo("Aceptar", btnAceptar);
    }//GEN-LAST:event_btnAceptarMouseExited

    public JTable getTablaAfiliados() {
        return tablaAfiliados;
    }

    public boolean isBtnVerActivo() {
        return btnVerActivo;
    }

    public JLabel getBtnAceptar() {
        return btnAceptar;
    }
    
    


    
    

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel fondoAfiliados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAfiliados;
    // End of variables declaration//GEN-END:variables
}
