/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author RYZEN
 */
public class PanelVentas extends javax.swing.JPanel {

    DefaultListModel modelo;
    DefaultListModel modeloCompra;
    /**
     * Creates new form PanelDashboard
     */
    public PanelVentas() {
        initComponents();
        setSize(1086, 503);
        modelo = new DefaultListModel();
        listaProductos.setModel(modelo);
        modeloCompra = new DefaultListModel();
        listaCompras.setModel(modeloCompra);
    }
    
    public void vaciarListaCompras()
    {
        modeloCompra.removeAllElements();
    }
    
    public void llenarListaProductos(ArrayList<String> productos){
        modelo.removeAllElements();
        for (String producto : productos)
            {
                modelo.addElement(producto);
            }
    }
    
    public ArrayList<String> getListaDeCompras()
    {
        ArrayList<String> auxLista = new ArrayList<String>();
        int size = modeloCompra.size();
        for (int i = 0; i < size; i++)
        {
            auxLista.add((String) modeloCompra.elementAt(i));
        }
        return auxLista;
    }
    
    public String getItemListaDeProductos(int _index)
    {
        return (String) modelo.getElementAt(_index);
    }
    
    public ArrayList<String> getListaDeProductos()
    {
        ArrayList<String> auxLista = new ArrayList<String>();
        int size = modelo.size();
        for (int i = 0; i < size; i++)
        {
            auxLista.add((String) modelo.elementAt(i));
        }
        return auxLista;
    }
    
    public String getProductoSeleccionado(){
        return listaProductos.getSelectedValue();
    }
    
    public int getCantidadProductosCompra()
    {
        return modeloCompra.size();
    }
    
    public void quitarElementoCompras(int _index)
    {
        modeloCompra.remove(_index);
    }
    
    public String getCompraSeleccionada()
    {
        return listaCompras.getSelectedValue();
    }
    
    public void setItemProducto(String _item, int _index)
    {
        modelo.setElementAt(_item, _index);
    }
    
    public void setItemCompra(String _item, int _index)
    {
        modeloCompra.setElementAt(_item, _index);
    }
    
    
    
    /*
    public void activarBotonAgregar(boolean estado){
        btnAgregarCantidad.setEnabled(estado); 
    }
    */
    
    public int getCantidadProductos(){
        return Integer.parseInt(txtCantidadProducto.getText());
    }
    
    public void setTxtPrecioTotal(float precioTotal){
        txtPrecio.setText(String.valueOf(precioTotal));
    }
    
    public void setTxtNumeroTotalDeProductos(int numeroTotalProductos){
        txtCantidadProducto.setText(String.valueOf(numeroTotalProductos));
    }
    
    
    public void addItemListaCompras(String _item)
    {
        modeloCompra.addElement(_item);
    }        
     
    
 
    public void setTxtCantidad(String _text)
    {
        txtCantidadProducto.setText(_text);
    }
    
    public String getTxtCantidad()
    {
        return txtCantidadProducto.getText();
    }
    
    public String getTxtPrecioTotal()
    {
        return txtPrecio.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrecio = new javax.swing.JTextField();
        txtCantidadProducto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCompras = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        fondoVentas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1086, 503));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrecio.setText("jTextField1");
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(936, 235, 130, 27));

        txtCantidadProducto.setText("jTextField1");
        add(txtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 130, 30));

        listaCompras.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaCompras.setMinimumSize(new java.awt.Dimension(45, 93));
        jScrollPane2.setViewportView(listaCompras);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 330, 300));

        listaProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaProductos.setMaximumSize(new java.awt.Dimension(45, 93));
        listaProductos.setMinimumSize(new java.awt.Dimension(45, 93));
        listaProductos.setPreferredSize(new java.awt.Dimension(48, 90));
        jScrollPane1.setViewportView(listaProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 330, 390));

        fondoVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenesPaneles/00-PanelDashboardFondo-img.png"))); // NOI18N
        add(fondoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1086, 503));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaCompras;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
